language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - redis-server

before_script:
  - composer install

script:
  - vendor/bin/phpspec run -f dot
  - vendor/bin/phpunit --colors --coverage-text
